---

- name: "copying the bahmnimaadi custom omod"
  copy:
    src: "/tmp/bahmnimaadi-1.0-SNAPSHOT.omod"
    dest: "/opt/openmrs/modules/bahmnimaadi-1.0-SNAPSHOT.omod"

- name: "copying the appointments omod"
  copy:
    src: "/tmp/appointments-1.1-SNAPSHOT.omod"
    dest: "/opt/openmrs/modules/appointments-1.1-SNAPSHOT.omod"

- name: "copying the bahmni core omod"
  copy:
    src: "/tmp/bahmnicore-0.91-SNAPSHOT.omod"
    dest: "/opt/openmrs/modules/bahmnicore-0.91-SNAPSHOT.omod"

- name: "delete previous appt module"
  file:
    path: /opt/openmrs/modules/appointment-*.omod
    state: absent

- name: "copying the bahmni apps"
  copy:
    src: "/tmp/bahmniapps.zip"
    dest: "/opt/bahmni-web/etc/bahmniapps.zip"

- name: "unlinking /var/www/bahmniapps"
  file:
    path: "/var/www/bahmniapps"
    state: absent
  when: "bahmniapps_url is defined"

- name: "Unzip downloaded bahmniapps file"
  unarchive:
    src: /tmp/bahmniapps.zip
    dest: /opt/bahmni-web/etc/bahmniapps

- name: "linking /var/www/bahmniapps to cairo bahmniapps"
  file:
    src: "/opt/bahmni-web/etc/bahmniapps"
    dest: "/var/www/bahmniapps"
    state: link
  when: "bahmniapps_url is defined"

- name: 'Unzip bahmnireports.war file'
  unarchive:
    dest: /opt/bahmni-reports/bahmni-reports
    src: /tmp/bahmnireports.war
