set @concept_id = 0;
set @concept_short_id = 0;
set @concept_full_id = 0;
set @count = 0;
set @uuid = NULL;

call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Ethiopian","Ethiopian",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Eritrean","Eritrean",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Sudan","Sudan",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"South Sudan","South Sudan",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Somali","Somali",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Syrian","Syrian",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Libyan","Libyan",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Iraqi","Iraqi",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Yemeni","Yemeni",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Nigerian","Nigerian",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Other","Other",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Arabic","Arabic",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Oromo","Oromo",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Amharic","Amharic",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Tigrinya","Tigrinya",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Tigre","Tigre",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Belene","Belene",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Dinka","Dinka",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Fur (Darfur)","Fur (Darfur)",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Zaghawa","Zaghawa",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Nuer","Nuer",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"English","English",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Masalit","Masalit",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"In-Scope","In-Scope",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Out-of-Scope","Out-of-Scope",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Health Promoter","Health Promoter",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Community","Community",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Partner","Partner",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Friend","Friend",'N/A','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Nationality","Nationality",'Coded','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Language","Language",'Coded','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"Patient's scope","Patient's scope",'Coded','Misc',false);
call add_concept(@concept_id,@concept_short_id,@concept_full_id,"How reach MSF","How reach MSF",'Coded','Misc',false);
